ATTRIBUTE_MAP = {
    'Case Number': 'case_id',
    'Citation Number': 'case_id',
    'Case Type': 'type',
    'Case Title': 'title',
    'Claim Type': 'type',
    'Case Disposition': 'disposition',
    'Case Status': 'status',
    'Complaint Status': 'status',
    'Vs': 'against',
    'Connection': 'type',
    'Connection to Complaint': 'type',
    'Party Type': 'type',
    'Business or Organization Name': 'bus_org_name',
    'Attorney\'s Firm': 'practice_name',
    'AgencyName': 'agency_name',
    'Zip Code': 'zip',
    'Event Type': 'type',
    'Event Date': 'date',
    'Event Time': 'time',
    'Charge Description': 'description',
    'Vehicle State': 'state',
    'Probable Cause Indicator': 'probable_cause',
    'Contributed to Accident': 'accident_contribution',
    'Convicted Speed': 'recorded_speed',
    'Seat Belts Used': 'seatbelts_used',
    'Personal Injury': 'injuries',
    'Charge Class': 'class',
    'Life/Death': 'jail_extreme_punishment',
    'Suspended Term': 'jail_suspended_term',
    'UnSuspended Term': 'jail_unsuspended_term',
    'Probation': 'probation_term',
    'Supervised': 'probation_supervised_term',
    'UnSupervised': 'probation_unsupervised_term',
    'First Pmt Due': 'fine_first_pmt_due',
    'Hours': 'cws_hours',
    'Complete By': 'cws_deadline',
    'Report To': 'cws_location',
    'Report Date': 'cws_date',
    'Document Name': 'name',
    'File Date': 'filing_date',
    'Entered Date': 'date',
    'Ordered Date': 'date',
    'Judgement Interest': 'interest',
    'PreJudgement Interest': 'interest',
    'Is Awarded To The': 'in_favor_of',
    'Amount': 'amt',
    'Amount of Judgement': 'amt',
}

def getAttributeName(label):
    attr = ATTRIBUTE_MAP.get(label)
    if not attr: attr = label.lower().replace(' ', '_')
    return attr

HEADER_MAP = {
    'Case Information': 'cases',
    'Plaintiff/Petitioner Information': 'parties',
    'Plaintiff': 'parties',
    'Surety': 'parties',
    'Bond Remitter/Bondsman': 'parties',
    'Officer - Arresting/Complainant': 'parties',
    'Attorney(s) for the Plaintiff/Petitioner': 'attorneys',
    'Attorney(s) for the Plaintiff': 'attorneys',
    'Defendant/Respondent Information': 'parties',
    'Defendant Information': 'parties',
    'Defendant': 'parties',
    'Attorney(s) for the Defendant/Respondent': 'attorneys',
    'Attorney(s) for the Defendant': 'attorneys',
    'Court Scheduling Information': 'events',
    'Case History Information': 'events',
    'ORIGINAL JUDGMENT': 'judgements',
    'Judgement Information': 'judgements',
    'Related Person Information': 'parties',
    'Related Persons Information': 'parties',
    'Attorney(s) for the Related Person': 'attorneys',
    'Charge and Disposition Information': 'charges',
    'Charge Information': 'charges',
    'Disposition': 'charges',
    'Document Tracking': 'documents',
    'Document Information': 'documents',
    'Complaint Information': 'complaints'
}

def getSectionName(title):
    return HEADER_MAP.get(title)
